# printWidth: 80 # 80
# tabWidth: 2 # 2
# useTabs: false # bool
semi: true # bool
# singleQuote: true # bool
trailingComma: all # none | es5 | all
bracketSpacing: true # bool
# jsxBracketSameLine: false # false
# arrowParens: avoid # avoid | always
